### ISSUE TITLE
Documentation for _image

### ISSUE THREAD

**Issue by jhamilx** [bennyrowland/suspect#7]
Is there any good documentation or explanation of the functionality of the _image module?

**Comment by bennyrowland** [comment]
@jhamilx image is there to handle working with MRI data for co-visualisation and soon for things like T2 correction. There isn't anything written about it yet, mainly because I am planning a big overhaul of the module to make it easier to work with and more consistent with the MRS data types. If you have any requests for new features please do open issues, but it is better to open them on the openmrslab/suspect fork which has supplanted this original.

**Comment by jhamilx** [comment]
Okay Ill post an issue in the other version.
