### ISSUE TITLE
import suspect error

### ISSUE THREAD

**Issue by cewelling** [bennyrowland/suspect#9]
Hello, 

I've just pip installed suspect and pydicom (with no errors).  Trying my first call to "import suspect", and receiving the following error (below).  Any tips on where this might be coming from?  

Thanks!
Caroline
```

 import suspect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/suspect/__init__.py", line 1, in <module>
    from suspect.mrsobjects import MRSBase, MRSData, MRSSpectrum
  File "/Library/Python/2.7/site-packages/suspect/mrsobjects.py", line 1, in <module>
    import suspect.base
  File "/Library/Python/2.7/site-packages/suspect/base.py", line 5, in <module>
    from . import _transforms
  File "/Library/Python/2.7/site-packages/suspect/_transforms.py", line 96
    positions = [*args, 1]
                 ^
SyntaxError: invalid syntax
```

**Comment by bennyrowland** [comment]
Hi Caroline,

Welcome to the suspect community, and sorry you have been having some trouble with it already. The problem here is that you are running Python v2.7 but suspect only supports Python v3. Python3 offers a lot of advantages over Python2, both in features and performance, which is why we decided to use it for suspect, and this is an example of some code which will not run in Python2.

Python3 is very easy to install, my preferred way is to use the anaconda distribution, as that comes with a lot of other scientific packages bundled and lives in the user space, so it doesn't interfere with any system Python that might be installed. You could also take a look at the OpenMRSLab Docker image which provides a Python/Jupyter installation with suspect installed as well as various other packages such as TARQUIN and FSL.

I had thought that pip would not install suspect on Python2, but it turns out there are some loopholes. I will look into fixing that so this kind of thing can't happen again. In the meantime, please let me know if you have any further problems getting started with Suspect.

Best,
Ben

**Comment by cewelling** [comment]
Hi Ben,

Thank you for the warm welcome!  Suspect is working perfectly now in python
3.6.

I am amazed by this incredible tool - thank you so much for making it
available to the MRS community!

Cheers,
Caroline

**Comment by bennyrowland** [comment]
Thanks, Caroline, good to hear that you have everything working. I will close this issue now, but please don't hesitate to open new ones if you have any more problems, or if you would like to request new features. Stuff tends to get implemented as and when people ask for it, so if you feel there is something useful missing, do let us know.
Ben
